const colors = {
  white: '#fff',
  lightBlue: '#17a8eb',
  blue: '#0892d1',
  darkBlue: '#047fb8',
  lightIndigo: '#69778c',
  indigo: '#62738c',
  darkIndigo: '#2e4466',
  lightRed: '#ffeeed',
  red: '#fa453e',
  lightGreen: '#e6f5dc',
  green: '#5c9936',
  grey: {
    offWhite: '#fafafa',
    lighterGrey: '#edeff0',
    lightGrey: '#cbcfd1',
    grey: '#94999c',
    darkGrey: '#72777a',
    darkerGrey: '#2e3133',
    gray9: '#171717',
  },
};

export default {
  palette: {
    login: {
      background: colors.grey.lighterGrey,
      text: colors.grey.darkerGrey,
      buttonBg: colors.darkBlue,
    },
    common: {
      black: colors.grey.darkerGrey,
      white: colors.white,
      transparent: 'rgba(0, 0, 0, 0)',
      fullBlack: 'rgba(0, 0, 0, 1)',
      green: colors.green,
      darkBlue: colors.darkBlue,
      lightGreen: colors.lightGreen,
      darkIndigo: colors.darkIndigo,
    },
    primary: {
      light: colors.lightBlue,
      main: colors.blue,
      dark: colors.darkBlue,
      contrastText: colors.white,
    },
    secondary: {
      light: colors.lightIndigo,
      main: colors.indigo,
      dark: colors.darkIndigo,
      contrastText: colors.white,
    },
    error: {
      light: colors.lightRed,
      main: colors.red,
      contrastText: colors.white,
      contrastLightRed: colors.grey,
    },
    success: {
      light: colors.lightGreen,
      main: colors.green,
      contrastText: colors.white,
      contrastLightGreen: colors.grey,
    },
    grey: {
      50: colors.grey.offWhite,
      100: colors.grey.lighterGrey,
      200: '#E0E0E0',
      300: colors.grey.lightGrey,
      400: '#98a2b3',
      500: colors.grey.grey,
      600: colors.indigo,
      700: '#616364',
      800: '#424242',
      900: '#212121',
      A100: '#d5d5d5',
      A200: '#aaaaaa',
      A400: colors.grey.darkGrey,
      A700: colors.grey.darkerGrey,
      contrastDefaultColor: 'dark',
      gray9: colors.grey.gray9,
    },
    active: '#d5e6ee',
    text: {
      primary: colors.grey.darkerGrey,
      secondary: '#98a2b3',
      disabled: colors.grey.lightGrey,
      hint: colors.grey.darkerGrey,
      icon: colors.grey.darkerGrey,
      divider: colors.grey.lightGrey,
      lightDivider: colors.grey.lightGrey,
      standarMarginLeft: 17,
    },
    bold: {
      fontWeight: '600',
    },
    // TODO: We need to deprecate item specific colors and non-palette values out. Please don't add more!
    searchInput: {
      background: colors.grey.offWhite,
      iconColor: '#98a2b3',
      placeholderTextColor: colors.grey.grey,
    },
    subHeaderText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.lightIndigo,
    },
    scheduleSubHeader: {
      backgroundColor: colors.grey.lighterGrey,
    },
    subInformation: {
      fontSize: 13,
    },
    title: {
      fontSize: 16,
      fontWeight: '600',
    },
    semiBold: {
      fontWeight: '400',
    },
    subTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.grey.lighterGrey,
    },
    shiftItem: {
      height: 140,
    },
    infoText: {
      color: colors.darkIndigo,
      fontSize: 14,
    },
  },
  container: {
    paddingTop: 20,
    paddingLeft: 16,
    paddingBottom: 8,
  },
  scrollContainer: {
    paddingBottom: 5,
  },
  header: {
    navBarSubtitleColor: 'rgba(255, 255, 255, 0.6)',
    buttonColor: colors.white,
    navBarSubtitleFontSize: 12,
    navBarTextFontSize: 18,
    navBarTextColor: colors.white,
  },
  spacing: {
    unit: 4, // multiply this for bigger spacing
    unit8: 8,
    unit12: 12,
    unit16: 16,
    unit20: 20,
    unit24: 24,
    unit28: 28,
    unit32: 32,
    unit48: 48,
  },
  size: {
    unit: 4,
    unit6: 6,
    unit8: 8,
    unit10: 10,
    unit12: 12,
    unit14: 14,
    unit16: 16,
    unit24: 24,
    unit44: 44,
    unit192: 192,
  },
  tab: {
    lineColor: colors.darkIndigo,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.darkerGrey,
    marginBottom: 2,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: colors.darkerGrey,
  },
  sectionContent: {
    fontSize: 14,
    color: colors.darkerGrey,
    fontWeight: '600',
    marginTop: 2,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
  },
  statusTextClosed: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.green,
  },
  statusUser: {
    fontSize: 12,
    color: colors.white,
  },
  statusUserClosed: {
    fontSize: 12,
    color: colors.grey.darkerGrey,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
    marginTop: 8,
    marginBottom: 8,
    marginLeft: 24,
    marginRight: 24,
  },
  dueDateText: {
    marginLeft: 10,
    marginRight: 15,
    fontSize: 16,
    color: colors.grey.darkerGrey,
  },
  dueDateDiffText: {
    fontSize: 16,
    color: colors.red,
  },
  customerContainer: {
    borderWidth: 1,
    borderColor: colors.grey.lighterGrey,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    padding: 10,
    paddingLeft: 15,
    top: -1,
  },
  linkText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.darkBlue,
  },
};
