const SHIFT_DETAIL_COMPONENT = {
  CLOCK_IN: 'SHIFT_DETAIL_COMPONENT.CLOCK_IN',
  CLOCK_OUT: 'SHIFT_DETAIL_COMPONENT.CLOCK_OUT',
  COVERAGE: 'SHIFT_DETAIL_COMPONENT.COVERAGE',
  INSTRUCTIONS: 'SHIFT_DETAIL_COMPONENT.INSTRUCTIONS',
};
export default SHIFT_DETAIL_COMPONENT;
