const LEGAL_PAGE = {
  TERMS_OF_SERVICE: {
    NAV_TITLE: 'LEGAL_PAGE.TERMS_OF_SERVICE.NAV_TITLE',
    TITLE: 'LEGAL_PAGE.TERMS_OF_SERVICE.TITLE',
    CONTENT: 'LEGAL_PAGE.TERMS_OF_SERVICE.CONTENT',
  },
  PRIVACY_STATEMENT: {
    NAV_TITLE: 'LEGAL_PAGE.PRIVACY_STATEMENT.NAV_TITLE',
    TITLE: 'LEGAL_PAGE.PRIVACY_STATEMENT.TITLE',
    CONTENT: 'LEGAL_PAGE.PRIVACY_STATEMENT.CONTENT',
  },
  SECURITY_POLICY: {
    NAV_TITLE: 'LEGAL_PAGE.SECURITY_POLICY.NAV_TITLE',
    TITLE: 'LEGAL_PAGE.SECURITY_POLICY.TITLE',
    CONTENT: 'LEGAL_PAGE.SECURITY_POLICY.CONTENT',
  },
};
export default LEGAL_PAGE;

