const AUTH_MODULE = {
  WELCOME: 'AUTH_MODULE.WELCOME',
  EMAIL: 'AUTH_MODULE.EMAIL',
  PASSWORD: 'AUTH_MODULE.PASSWORD',
  SIGN_IN: 'AUTH_MODULE.SIGN_IN',
  FORGOT_PASSWORD: 'AUTH_MODULE.FORGOT_PASSWORD',
  LOG_OUT: 'AUTH_MODULE.LOG_OUT',
  CLOSE: 'AUTH_MODULE.CLOSE',
};
export default AUTH_MODULE;
